# Generated by Django 5.2.8 on 2025-11-29 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_name", models.TextField()),
                ("sender_email", models.TextField()),
                ("recipient_name", models.TextField()),
                ("recipient_email", models.TextField()),
                ("subject", models.TextField()),
                ("date", models.TextField()),
                ("message_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {
                    (
                        "sender_name",
                        "sender_email",
                        "recipient_name",
                        "recipient_email",
                        "subject",
                        "date",
                        "message_content",
                    )
                },
            },
        ),
    ]
