# Generated by Django 5.2.8 on 2025-11-30 09:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name='LLMAnalysis',
			fields=[
				(
					'id',
					models.UUIDField(
						default=uuid.uuid4,
						editable=False,
						primary_key=True,
						serialize=False,
					),
				),
				('encrypted_question', models.TextField(null=True)),
				('encrypted_answer', models.TextField(null=True)),
			],
		),
		migrations.CreateModel(
			name='Email',
			fields=[
				(
					'id',
					models.UUIDField(
						default=uuid.uuid4,
						editable=False,
						primary_key=True,
						serialize=False,
					),
				),
				('encrypted_sender_name', models.TextField(null=True)),
				('encrypted_sender_email', models.TextField(null=True)),
				('encrypted_recipient_name', models.TextField(null=True)),
				('encrypted_recipient_email', models.TextField(null=True)),
				('encrypted_subject', models.TextField(null=True)),
				('encrypted_summary', models.TextField(null=True)),
				('encrypted_date', models.TextField(null=True)),
				('encrypted_message_content', models.TextField(null=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
			],
			options={
				'unique_together': {
					(
						'encrypted_sender_name',
						'encrypted_sender_email',
						'encrypted_recipient_name',
						'encrypted_recipient_email',
						'encrypted_subject',
						'encrypted_summary',
						'encrypted_date',
						'encrypted_message_content',
					)
				},
			},
		),
	]
