# Generated by Django 5.2.8 on 2025-11-29 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backendApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField(null=True)),
                ("answer", models.TextField(null=True)),
            ],
        ),
    ]
