# Generated by Django 5.2.8 on 2025-11-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='encrypted_category',
            field=models.TextField(null=True),
        ),
    ]
