# Generated by Django 5.2.8 on 2025-11-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('backendApp', '0003_stakeholder'),
	]

	operations = [
		migrations.AddField(
			model_name='email',
			name='stakeholders',
			field=models.ManyToManyField(blank=True, to='backendApp.stakeholder'),
		),
	]
