# Generated by Django 5.2.8 on 2025-11-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_email_stakeholders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='stakeholders',
        ),
        migrations.DeleteModel(
            name='Stakeholder',
        ),
    ]
