# Generated by Django 5.2.8 on 2025-11-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_remove_email_stakeholders_delete_stakeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='encrypted_project_name',
        ),
        migrations.RemoveField(
            model_name='email',
            name='encrypted_timeline',
        ),
    ]
